name: Deploy Lambda Layer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Choose the Python version you need

    - name: Install AWS CLI
      run: |
        pip install awscli
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Create Lambda Layer Directory
      run: |
        mkdir -p lambda_layer/python

    - name: Install Lambda Dependencies
      run: |
        pip install -r src/requirements.txt -t lambda_layer/python

    - name: Zip Lambda Layer
      run: |
        cd lambda_layer && zip -r ../lambda_dependencies.zip .

    - name: Upload Lambda Layer to S3
      run: |
        aws s3 cp lambda_dependencies.zip s3://sis-24-bucket/

